---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "4c6191fc-112g-99aa-9219-555a9ef6d999",
        "monitors": [
          "1.1.1.1:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config